# Generated by Django 4.2.7 on 2023-11-28 04:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contact",
            name="description",
        ),
        migrations.RemoveField(
            model_name="contact",
            name="is_done",
        ),
        migrations.AddField(
            model_name="contact",
            name="created_time",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contact",
            name="email",
            field=models.TextField(default="", max_length=50),
        ),
    ]
